### ISSUE TITLE
 onGenerateRoute: Router.generateRoute Error

### ISSUE THREAD

**Issue by basharbachir** [obnil/flutter_music_app#10]
hi, there is no generateRoute in  Router Class,
can you please update the class.
thanks in advance

**Comment by nvtanhh** [comment]
I got the same problem.

**Comment by obnil** [comment]
```
import 'config/router_manager.dart' as Router;

onGenerateRoute: Router.Router.generateRoute,
initialRoute: Router.RouteName.splash,
```

**Comment by obnil** [comment]
> hi, there is no generateRoute in Router Class,
> can you please update the class.
> thanks in advance

here is the solution
