### ISSUE TITLE
Error installing debug

### ISSUE THREAD

**Issue by ElaineSchwner** [obnil/flutter_music_app#7]
Hello, I am trying to install on debug mode, and I get this error:
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

Do you have any idea how I can fix?

**Comment by obnil** [comment]
android {
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a','x86_64'
            universalApk true
        }
    }
}

**Comment by obnil** [comment]
> Hello, I am trying to install on debug mode, and I get this error:
> Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
> 
> Do you have any idea how I can fix?

android {
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a','x86_64'
            universalApk true
        }
    }
}

**Comment by obnil** [comment]
> Hello, I am trying to install on debug mode, and I get this error:
> Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
> 
> Do you have any idea how I can fix?

```
android {
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a','x86_64'
            universalApk true
        }
    }
}
```

**Comment by oficinaiot** [comment]
Hello, it didn't work for me.

**Comment by Chandra-shekar-shetty** [comment]
@oficinaiot
In app build.gradle   remove code
      ndk {
            abiFilters "armeabi", "x86", "armeabi-v7a"
        }

**Comment by obnil** [comment]
I need more detail or you can contact me

发自我的iPhone

**Comment by sulmanyousaf** [comment]
> @oficinaiot
> In app build.gradle remove code
> ndk {
> abiFilters "armeabi", "x86", "armeabi-v7a"
> }

Thanks this work for me but can you help me more it make this app fully functional as i think it's just a UI not a functional app.
Please message me on this whatsapp number +923355219298
or email at sulmanyousaf86@gmail.com

**Comment by obnil** [comment]
> > @oficinaiot
> > In app build.gradle remove code
> > ndk {
> > abiFilters "armeabi", "x86", "armeabi-v7a"
> > }
> 
> Thanks this work for me but can you help me more it make this app fully functional as i think it's just a UI not a functional app.
> Please message me on this whatsapp number +923355219298
> or email at [sulmanyousaf86@gmail.com](mailto:sulmanyousaf86@gmail.com)

ok, I will message you with your whatsapp number
